name: "🐞 Bug"
description: "버그 리포트"
labels: ["bug"]
body:
  - type: textarea
    attributes:
      label: "🐛 설명"

  - type: textarea
    id: bug_description
    attributes:
      label: "📌 발생한 문제"
      description: "어떤 문제가 발생했나요? 예상한 동작과 실제 동작을 설명해주세요."
    validations:
      required: true

  - type: textarea
    id: steps_to_reproduce
    attributes:
      label: "⚡ 발생 경로"
      description: "버그가 발생하게된 경로를 설명해주세요."
      placeholder: |
        1. 로그인 페이지로 이동
        2. 이메일과 비밀번호 입력 후 로그인 버튼 클릭
        3. 아무 반응이 없음
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: "📝 오류 로그 (선택)"
      description: "콘솔 로그나 오류 메시지가 있다면 첨부해주세요."
      render: shell